<?php
/**
 * /llms.txt
 *
 * A plain text summary of the site for language models: what this is, who
 * runs it, the pages that matter and how to get in touch. The format is a
 * convention rather than a standard, which is exactly why it is worth
 * serving: it costs one file and it is the only place where a site can say in
 * its own words what it wants to be quoted as.
 *
 * Everything in it already exists elsewhere on the site. Nothing here is a
 * second place to maintain: the title and tagline come from Settings, the
 * business details from the schema fields, the page list from the pages that
 * are published and not hidden from search engines.
 *
 * Served from a request handler rather than a rewrite rule, so no permalinks
 * have to be flushed and nothing breaks if they are.
 *
 * @package BasaltCore
 */

defined( 'ABSPATH' ) || exit;

/** How long the generated file is kept. */
const BASALT_CORE_LLMS_TTL = 12 * HOUR_IN_SECONDS;

/**
 * Answer /llms.txt.
 *
 * @return void
 */
function basalt_core_llms_route(): void {
	if ( ! basalt_core_get( 'llms_enabled' ) ) {
		return;
	}

	$path = (string) wp_parse_url( (string) ( $_SERVER['REQUEST_URI'] ?? '' ), PHP_URL_PATH );
	$home = (string) wp_parse_url( home_url(), PHP_URL_PATH );

	if ( '' !== $home && '/' !== $home && str_starts_with( $path, $home ) ) {
		$path = substr( $path, strlen( $home ) );
	}

	if ( 'llms.txt' !== trim( $path, '/' ) ) {
		return;
	}

	$body = get_transient( 'basalt_core_llms' );

	if ( ! is_string( $body ) || '' === $body ) {
		$body = basalt_core_llms_build();
		set_transient( 'basalt_core_llms', $body, BASALT_CORE_LLMS_TTL );
	}

	status_header( 200 );
	header( 'Content-Type: text/plain; charset=utf-8' );
	header( 'X-Robots-Tag: noindex' );
	echo $body; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- plain text, escaped as it is built.
	exit;
}
add_action( 'parse_request', 'basalt_core_llms_route', 1 );

/**
 * Build the file.
 *
 * @return string
 */
function basalt_core_llms_build(): string {
	$name    = wp_specialchars_decode( (string) get_bloginfo( 'name' ), ENT_QUOTES );
	$tagline = wp_specialchars_decode( (string) get_bloginfo( 'description' ), ENT_QUOTES );
	$intro   = trim( (string) basalt_core_get( 'llms_intro' ) );

	$out   = array();
	$out[] = '# ' . $name;
	$out[] = '';

	if ( '' !== $tagline ) {
		$out[] = '> ' . $tagline;
		$out[] = '';
	}

	if ( '' !== $intro ) {
		$out[] = $intro;
		$out[] = '';
	}

	$pages = basalt_core_llms_pages();

	if ( $pages ) {
		$out[] = '## Pages';
		$out[] = '';

		foreach ( $pages as $page ) {
			$line = sprintf( '- [%1$s](%2$s)', $page['title'], $page['url'] );

			if ( '' !== $page['note'] ) {
				$line .= ': ' . $page['note'];
			}

			$out[] = $line;
		}

		$out[] = '';
	}

	$contact = basalt_core_llms_contact();

	if ( $contact ) {
		$out[] = '## Contact';
		$out[] = '';

		foreach ( $contact as $line ) {
			$out[] = '- ' . $line;
		}

		$out[] = '';
	}

	$out[] = '## More';
	$out[] = '';
	$out[] = '- [Sitemap](' . esc_url_raw( home_url( '/wp-sitemap.xml' ) ) . ')';
	$out[] = '';
	$out[] = sprintf(
		'_Generated by the site on %s. Quote it with a link back to the page you took it from._',
		wp_date( 'Y-m-d' )
	);
	$out[] = '';

	/**
	 * Filter the finished llms.txt.
	 *
	 * @param string $body The file contents.
	 */
	return (string) apply_filters( 'basalt_core_llms_txt', implode( "\n", $out ) );
}

/**
 * The pages worth listing.
 *
 * Published pages that are not hidden from search engines, front page first,
 * then whatever order the site put them in. Capped, because a list of two
 * hundred pages is not a summary.
 *
 * @return array<int, array{title: string, url: string, note: string}>
 */
function basalt_core_llms_pages(): array {
	$found = get_posts(
		array(
			'post_type'        => 'page',
			'post_status'      => 'publish',
			'numberposts'      => 30,
			'orderby'          => array( 'menu_order' => 'ASC', 'title' => 'ASC' ),
			'suppress_filters' => false,
			'meta_query'       => array( // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query -- thirty pages, twice a day.
				'relation' => 'OR',
				array(
					'key'     => '_basalt_noindex',
					'compare' => 'NOT EXISTS',
				),
				array(
					'key'   => '_basalt_noindex',
					'value' => '0',
				),
			),
		)
	);

	$front = (int) get_option( 'page_on_front' );
	$pages = array();
	$skip  = basalt_core_llms_skipped_pages();

	foreach ( $found as $post ) {
		if ( in_array( (int) $post->ID, $skip, true ) || '' !== (string) $post->post_password ) {
			continue;
		}

		$note = has_excerpt( $post ) ? wp_strip_all_tags( (string) get_the_excerpt( $post ) ) : '';
		$note = html_entity_decode( trim( preg_replace( '/\s+/', ' ', $note ) ?? '' ), ENT_QUOTES );

		$entry = array(
			'title' => html_entity_decode( wp_strip_all_tags( (string) get_the_title( $post ) ), ENT_QUOTES ),
			'url'   => (string) get_permalink( $post ),
			'note'  => mb_substr( $note, 0, 160 ),
		);

		if ( $front && $front === $post->ID ) {
			array_unshift( $pages, $entry );
			continue;
		}

		$pages[] = $entry;
	}

	/**
	 * Filter the pages listed in llms.txt.
	 *
	 * @param array<int, array{title: string, url: string, note: string}> $pages The list.
	 */
	return (array) apply_filters( 'basalt_core_llms_pages', $pages );
}

/**
 * Pages that are plumbing rather than content.
 *
 * A cart, a checkout and an account page describe nothing about the business
 * and are useless to somebody answering a question about it.
 *
 * @return int[]
 */
function basalt_core_llms_skipped_pages(): array {
	$skip = array();

	if ( function_exists( 'wc_get_page_id' ) ) {
		foreach ( array( 'cart', 'checkout', 'myaccount' ) as $page ) {
			$id = (int) wc_get_page_id( $page );

			if ( $id > 0 ) {
				$skip[] = $id;
			}
		}
	}

	$privacy = (int) get_option( 'wp_page_for_privacy_policy' );

	if ( $privacy > 0 ) {
		$skip[] = $privacy;
	}

	/**
	 * Filter the pages left out of llms.txt.
	 *
	 * @param int[] $skip Page IDs.
	 */
	return array_map( 'intval', (array) apply_filters( 'basalt_core_llms_skipped_pages', $skip ) );
}

/**
 * The contact lines, from the details the schema graph already uses.
 *
 * @return string[]
 */
function basalt_core_llms_contact(): array {
	$lines   = array();
	$street  = (string) basalt_core_get( 'street' );
	$city    = trim( (string) basalt_core_get( 'postal_code' ) . ' ' . (string) basalt_core_get( 'city' ) );
	$phone   = (string) basalt_core_get( 'phone' );
	$email   = (string) basalt_core_get( 'email' );
	$hours   = (string) basalt_core_get( 'opening_hours' );

	if ( '' !== $street || '' !== $city ) {
		$lines[] = trim( 'Address: ' . trim( $street . ', ' . $city, ', ' ) );
	}

	if ( '' !== $phone ) {
		$lines[] = 'Phone: ' . $phone;
	}

	if ( '' !== $email ) {
		$lines[] = 'Email: ' . $email;
	}

	if ( '' !== $hours ) {
		$lines[] = 'Opening hours: ' . implode( '; ', basalt_core_parse_lines( $hours ) );
	}

	return $lines;
}

/**
 * Throw the cached file away when the site changes.
 *
 * @return void
 */
function basalt_core_llms_flush(): void {
	delete_transient( 'basalt_core_llms' );
}
add_action( 'save_post_page', 'basalt_core_llms_flush' );
add_action( 'deleted_post', 'basalt_core_llms_flush' );
add_action( 'update_option_' . BASALT_CORE_OPTION, 'basalt_core_llms_flush' );
add_action( 'update_option_blogname', 'basalt_core_llms_flush' );
add_action( 'update_option_blogdescription', 'basalt_core_llms_flush' );
